# Tensor Product of Qubit States using NumPy

We demonstrate how to compute the tensor product (Kronecker product) of single-qubit states using numpy`.





In [5]:
import numpy as np
# Define single-qubit basis states
ket0 = np.array([1, 0])
ket1 = np.array([0, 1])

# Tensor product using np.kron
tensor_00 = np.kron(ket0, ket0)
tensor_01 = np.kron(ket0, ket1)
tensor_super = np.kron((ket0 + ket1) / np.sqrt(2), ket0)

print("Tensor product |0⟩ ⊗ |0⟩:\n", tensor_00)
print("Tensor product |0⟩ ⊗ |1⟩:\n", tensor_01)
print("Tensor product (|0⟩ + |1⟩)/√2 ⊗ |0⟩:\n", tensor_super)


Tensor product |0⟩ ⊗ |0⟩:
 [1 0 0 0]
Tensor product |0⟩ ⊗ |1⟩:
 [0 1 0 0]
Tensor product (|0⟩ + |1⟩)/√2 ⊗ |0⟩:
 [0.70710678 0.         0.70710678 0.        ]


### Tensor Product of $|+\rangle$ and $|i^-\rangle$

We compute the tensor product of two single-qubit quantum states:

- $|+\rangle = \frac{1}{\sqrt{2}} \left( |0\rangle + |1\rangle \right)$  
- $|i^-\rangle = \frac{1}{\sqrt{2}} \left( |0\rangle - i|1\rangle \right)$

Their tensor product yields a 2-qubit quantum state:

$$
|\Psi\rangle = |+\rangle \otimes |i^-\rangle =
\frac{1}{2} \left( |00\rangle - i|01\rangle + |10\rangle - i|11\rangle \right)
$$

We use NumPy to compute this tensor product using `np.kron`:


In [6]:
import numpy as np

# Define basis states
ket0 = np.array([1, 0])
ket1 = np.array([0, 1])

# Define |+> = (|0⟩ + |1⟩) / √2
ket_plus = (ket0 + ket1) / np.sqrt(2)

# Define |i-> = (|0⟩ - i|1⟩) / √2
ket_i_minus = (ket0 - 1j * ket1) / np.sqrt(2)

# Tensor product
tensor_plus_i_minus = np.kron(ket_plus, ket_i_minus)

# Display result
print("Tensor product |+⟩ ⊗ |i⁻⟩:\n", tensor_plus_i_minus)


Tensor product |+⟩ ⊗ |i⁻⟩:
 [0.5+0.j  0. -0.5j 0.5+0.j  0. -0.5j]


### Tensor Product of Quantum Gates

In quantum computing, the tensor product is used to combine gates acting on separate qubits.

For example, applying a Hadamard gate to the **first qubit** and the Identity gate to the **second qubit** is expressed as:


In [3]:
# Define Hadamard and Identity gates
H = (1 / np.sqrt(2)) * np.array([[1, 1],
                                 [1, -1]])

I = np.eye(2)

# Compute the tensor product
H_tensor_I = np.kron(H, I)

print("H ⊗ I =\n", H_tensor_I)


H ⊗ I =
 [[ 0.70710678  0.          0.70710678  0.        ]
 [ 0.          0.70710678  0.          0.70710678]
 [ 0.70710678  0.         -0.70710678 -0.        ]
 [ 0.          0.70710678 -0.         -0.70710678]]


### Creating a Bell State using NumPy

We demonstrate how to create a **Bell state** using matrix operations in NumPy by simulating a 2-qubit quantum circuit composed of:

1. A **Hadamard gate** applied to the first qubit  
2. A **CNOT gate** (control: qubit 0, target: qubit 1)

---

#### Input State

We begin with the initial state:

$$
|00\rangle = \begin{bmatrix} 1 \\ 0 \\ 0 \\ 0 \end{bmatrix}
$$

---

#### Step 1: Apply \( H \otimes I \)

This applies a Hadamard gate to the first qubit only:

$$
H = \frac{1}{\sqrt{2}} \begin{bmatrix} 1 & 1 \\ 1 & -1 \end{bmatrix}, \quad
H \otimes I =
\frac{1}{\sqrt{2}}
\begin{bmatrix}
1 & 0 & 1 & 0 \\
0 & 1 & 0 & 1 \\
1 & 0 & -1 & 0 \\
0 & 1 & 0 & -1
\end{bmatrix}
$$

This transforms the system into:

$$
(H \otimes I)|00\rangle = \frac{1}{\sqrt{2}}(|00\rangle + |10\rangle)
$$

---

#### Step 2: Apply CNOT

The **CNOT gate** flips the second qubit if the first qubit is \( |1\rangle \):

$$
\text{CNOT} =
\begin{bmatrix}
1 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 \\
0 & 0 & 0 & 1 \\
0 & 0 & 1 & 0
\end{bmatrix}
$$

Applying CNOT results in:

$$
|\Phi^+\rangle = \frac{1}{\sqrt{2}} (|00\rangle + |11\rangle)
$$

This is one of the four **maximally entangled Bell states**.

---

### Summary

We have implemented the Bell-state preparation circuit entirely using NumPy:

1. Apply \( H \otimes I \) to \( |00\rangle \)  
2. Apply CNOT  
3. Resulting state:  
   $$
   \frac{1}{\sqrt{2}}(|00\rangle + |11\rangle)
   $$


In [9]:
import numpy as np

# Step 1: Define Hadamard and Identity gates
H = (1 / np.sqrt(2)) * np.array([[1, 1],
                                 [1, -1]])
I = np.eye(2)

# H ⊗ I — Apply Hadamard to the first qubit
H_tensor_I = np.kron(H, I)
print("H ⊗ I =\n", H_tensor_I)

# Step 2: Define CNOT gate (control: qubit 0, target: qubit 1)
CNOT = np.array([[1, 0, 0, 0],
                 [0, 1, 0, 0],
                 [0, 0, 0, 1],
                 [0, 0, 1, 0]])

print("\nCNOT =\n", CNOT)

# Step 3: Define input state |00⟩
ket00 = np.array([1, 0, 0, 0])
print("\n|00⟩ =\n", ket00)

# Step 4: Apply (CNOT ⋅ H ⊗ I) ⋅ |00⟩
state_after_H = H_tensor_I @ ket00
print("\n(H ⊗ I) |00⟩ =\n", state_after_H)

final_state = CNOT @ state_after_H
print("\nFinal state after CNOT ⋅ (H ⊗ I) |00⟩ =\n", final_state)


H ⊗ I =
 [[ 0.70710678  0.          0.70710678  0.        ]
 [ 0.          0.70710678  0.          0.70710678]
 [ 0.70710678  0.         -0.70710678 -0.        ]
 [ 0.          0.70710678 -0.         -0.70710678]]

CNOT =
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 0 1]
 [0 0 1 0]]

|00⟩ =
 [1 0 0 0]

(H ⊗ I) |00⟩ =
 [0.70710678 0.         0.70710678 0.        ]

Final state after CNOT ⋅ (H ⊗ I) |00⟩ =
 [0.70710678 0.         0.         0.70710678]
