# Eigenvalues and Eigenvectors in Python

## NumPy 

In [1]:
import numpy as np

# Create a square matrix
matrix = np.array([[1, 0],
                   [0,  -1]])

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

print("Eigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)


Eigenvalues:
[ 1. -1.]

Eigenvectors:
[[1. 0.]
 [0. 1.]]


## SciPy

In [2]:
import numpy as np
from scipy.linalg import eig

# Create a square matrix
matrix = np.array([[3, 1],
                   [1,  3]])

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = eig(matrix)

print("Eigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)


Eigenvalues:
[4.+0.j 2.+0.j]

Eigenvectors:
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


## Eigenvectors and Eigenvalues of X gate

In [3]:
import numpy as np

# Create a square matrix
matrix = np.array([[0, 1],
                   [1, 0]])

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

print("Eigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)


Eigenvalues:
[ 1. -1.]

Eigenvectors:
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
